### ISSUE TITLE
F2 button not working

### ISSUE THREAD

**Issue by dinokent** [friendlyarm/NanoHatOLED#2]
Hi, 
After somedays of playing, I moved the Nanopi Neo2 with OLED Hat to another location, after config the network and reboot, the OLED hat can only function with button F1 and F3. F2 to display IP / CPU... were no response. I do reinstall and reboot but no luck.

It can only show Time, and let me Shutdown now, any hints to fix it?
thx,
Kent

**Comment by friendlyarm** [comment]
Hello, try to remove the case, can the button F2 work?

**Comment by dinokent** [comment]
Hi,
Already tried without case but no luck.

This is my 2nd time re-install the OS, it seem problem was after I updated / install Python, but not really try it everytime I install new apps… anyway I will keep trying

thanks,
Kent

**Comment by friendlyarm** [comment]
ok, you also can try the new rom, download from this link (under the officail-ROMs directory):   https://www.mediafire.com/folder/ah4i6w029912b/NanoPi-NEO2

filename:   nanopi-neo2_ubuntu-oled_4.11.2_20170705.img.zip

**Comment by dinokent** [comment]
Ok thanks! I am download it again and test.

BTW, the current ROM I am using is DietPi, do the OLEDHat not compatible with other ROM / OS?

thx!!

**Comment by friendlyarm** [comment]
We haven't tested it on other OS, you can try to install it on other OS with the following commands:
```
# git clone https://github.com/friendlyarm/NanoHatOLED.git
# cd NanoHatOLED
# sudo -H ./install.sh
```

**Comment by dinokent** [comment]
just try a new flash the OS 20170705 , and reinstall the NanoHatOLED, still the same…

strange…. I won’t think it was the button problem… P1 and P3 working pretty well…..

**Comment by vophatechnicus** [comment]
"same" problem here. 

Display is working fine. Buttons F1 and F3 are working as expected.
But as soon as i press F2, the time display stops working (freezes) and any other button press (even F1 or F3) has no effect.

I installed it via Github repo over nanopi-neo-air_eflasher_4.11.2_20170705.img

**Comment by friendlyarm** [comment]
I'm sorry, it's an issue. Now you can fix it this way: 

cd ~/NanoHatOLED/BakeBit/
sudo git checkout master
sudo git pull
sudo reboot

**Comment by dinokent** [comment]
Dear all,

just update, but no luck.

Already remove the whole NanoHatOLED folder and reinstall and still the same.

thanks,
Kent

**Comment by vophatechnicus** [comment]
The fix doesn´t work.
But i have some new information. I Stopped the bakebit_nanhoat_oled.py process and startet the Python script by hand, so i could see the "Kx pressed" output. 

If i press K2 the message "K2 pressed" appears but nothuing happens. After some more presses the following error appers.

K2 pressed
Traceback (most recent call last):
  File "bakebit_nanohat_oled.py", line 286, in <module>
    time.sleep(1)
  File "bakebit_nanohat_oled.py", line 240, in receive_signal
    draw_page()
  File "bakebit_nanohat_oled.py", line 156, in draw_page
    draw.text((x, top+5),       "IP: " + str(IP),  font=smartFont, fill=255)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageDraw.py", line 209, in text
    *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageDraw.py", line 233, in multiline_text
    line_width, line_height = self.textsize(line, font)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageDraw.py", line 260, in textsize
    return font.getsize(text, direction, features)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFont.py", line 156, in getsize
    size, offset = self.font.getsize(text, direction, features)

I am not that deep into python but i hope it helps.

**Comment by vophatechnicus** [comment]
update:

as mentioned on a russian website with nearly the same error (for another thing) i tried to revert Pillow from installed version 4.2.1 to 4.1.1. 

Now it works!

**Comment by friendlyarm** [comment]
thanks,  we've released a new version of rom: nanopi-neo-air_ubuntu-oled_4.11.2_20170809.img.zip
download url: https://www.mediafire.com/index.php#oc15bwqbuxgxe
I tested it on NanoPi NEO Air and it works.
